bin_path: ${BINARY_PATH}
piddir: /var/run/
update_frequency: 10s
cache_retention_duration: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
api_url: http://localhost:8080/
api_key: ${API_KEY}
gaius_url: https://messagebus.asians.cloud/
gaius_token: 123
